# Generated by Django 5.2.10 on 2026-01-26 02:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.BigIntegerField(verbose_name='Criado em (timestamp)')),
                ('updated_at', models.BigIntegerField(verbose_name='Atualizado em (timestamp)')),
                ('deleted_at', models.BigIntegerField(blank=True, null=True, verbose_name='Deletado em (timestamp)')),
                ('sync_version', models.BigIntegerField(db_index=True, default=0, verbose_name='Versão de sync')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('date', models.CharField(db_index=True, max_length=10, verbose_name='Data')),
                ('start_time', models.IntegerField(verbose_name='Início (minutos desde meia-noite)')),
                ('end_time', models.IntegerField(verbose_name='Fim (minutos desde meia-noite)')),
                ('color', models.CharField(blank=True, max_length=20, verbose_name='Cor')),
                ('task_id', models.UUIDField(blank=True, null=True, verbose_name='Tarefa')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Recorrente')),
                ('recurrence_pattern', models.JSONField(blank=True, null=True, verbose_name='Padrão de recorrência')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Bloco de Calendário',
                'verbose_name_plural': 'Blocos de Calendário',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.BigIntegerField(verbose_name='Criado em (timestamp)')),
                ('updated_at', models.BigIntegerField(verbose_name='Atualizado em (timestamp)')),
                ('deleted_at', models.BigIntegerField(blank=True, null=True, verbose_name='Deletado em (timestamp)')),
                ('sync_version', models.BigIntegerField(db_index=True, default=0, verbose_name='Versão de sync')),
                ('objective', models.CharField(max_length=500, verbose_name='Objetivo')),
                ('deadline', models.CharField(blank=True, max_length=10, verbose_name='Prazo')),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('completed', 'Concluída'), ('archived', 'Arquivada')], default='active', max_length=20, verbose_name='Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Meta',
                'verbose_name_plural': 'Metas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.BigIntegerField(verbose_name='Criado em (timestamp)')),
                ('updated_at', models.BigIntegerField(verbose_name='Atualizado em (timestamp)')),
                ('deleted_at', models.BigIntegerField(blank=True, null=True, verbose_name='Deletado em (timestamp)')),
                ('sync_version', models.BigIntegerField(db_index=True, default=0, verbose_name='Versão de sync')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('frequency', models.CharField(choices=[('daily', 'Diário'), ('weekly', 'Semanal'), ('custom', 'Personalizado')], default='daily', max_length=20, verbose_name='Frequência')),
                ('target_days', models.JSONField(default=list, verbose_name='Dias alvo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('color', models.CharField(blank=True, max_length=20, verbose_name='Cor')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Ícone')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Hábito',
                'verbose_name_plural': 'Hábitos',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='InboxItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.BigIntegerField(verbose_name='Criado em (timestamp)')),
                ('updated_at', models.BigIntegerField(verbose_name='Atualizado em (timestamp)')),
                ('deleted_at', models.BigIntegerField(blank=True, null=True, verbose_name='Deletado em (timestamp)')),
                ('sync_version', models.BigIntegerField(db_index=True, default=0, verbose_name='Versão de sync')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('item_type', models.CharField(choices=[('note', 'Nota'), ('task', 'Tarefa'), ('idea', 'Ideia'), ('link', 'Link')], default='note', max_length=20, verbose_name='Tipo')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Processado')),
                ('processed_at', models.BigIntegerField(blank=True, null=True, verbose_name='Processado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Item da Inbox',
                'verbose_name_plural': 'Itens da Inbox',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KeyResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.BigIntegerField(verbose_name='Criado em (timestamp)')),
                ('updated_at', models.BigIntegerField(verbose_name='Atualizado em (timestamp)')),
                ('deleted_at', models.BigIntegerField(blank=True, null=True, verbose_name='Deletado em (timestamp)')),
                ('sync_version', models.BigIntegerField(db_index=True, default=0, verbose_name='Versão de sync')),
                ('goal_id', models.UUIDField(db_index=True, verbose_name='Meta')),
                ('description', models.CharField(max_length=500, verbose_name='Descrição')),
                ('target_value', models.FloatField(verbose_name='Valor alvo')),
                ('current_value', models.FloatField(default=0, verbose_name='Valor atual')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='Unidade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Resultado Chave',
                'verbose_name_plural': 'Resultados Chave',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PomodoroSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.BigIntegerField(verbose_name='Criado em (timestamp)')),
                ('updated_at', models.BigIntegerField(verbose_name='Atualizado em (timestamp)')),
                ('deleted_at', models.BigIntegerField(blank=True, null=True, verbose_name='Deletado em (timestamp)')),
                ('sync_version', models.BigIntegerField(db_index=True, default=0, verbose_name='Versão de sync')),
                ('session_type', models.CharField(choices=[('work', 'Trabalho'), ('break', 'Pausa'), ('long_break', 'Pausa longa')], default='work', max_length=20, verbose_name='Tipo')),
                ('duration_minutes', models.IntegerField(verbose_name='Duração (minutos)')),
                ('started_at', models.BigIntegerField(verbose_name='Iniciado em')),
                ('ended_at', models.BigIntegerField(blank=True, null=True, verbose_name='Finalizado em')),
                ('task_id', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='Tarefa')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Sessão Pomodoro',
                'verbose_name_plural': 'Sessões Pomodoro',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.BigIntegerField(verbose_name='Criado em (timestamp)')),
                ('updated_at', models.BigIntegerField(verbose_name='Atualizado em (timestamp)')),
                ('deleted_at', models.BigIntegerField(blank=True, null=True, verbose_name='Deletado em (timestamp)')),
                ('sync_version', models.BigIntegerField(db_index=True, default=0, verbose_name='Versão de sync')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('on_hold', 'Em espera'), ('completed', 'Concluído'), ('archived', 'Arquivado')], default='active', max_length=20, verbose_name='Status')),
                ('color', models.CharField(blank=True, max_length=20, verbose_name='Cor')),
                ('deadline', models.CharField(blank=True, max_length=10, verbose_name='Prazo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.BigIntegerField(verbose_name='Criado em (timestamp)')),
                ('updated_at', models.BigIntegerField(verbose_name='Atualizado em (timestamp)')),
                ('deleted_at', models.BigIntegerField(blank=True, null=True, verbose_name='Deletado em (timestamp)')),
                ('sync_version', models.BigIntegerField(db_index=True, default=0, verbose_name='Versão de sync')),
                ('title', models.CharField(max_length=500, verbose_name='Título')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('status', models.CharField(choices=[('todo', 'A fazer'), ('in_progress', 'Em progresso'), ('done', 'Concluído')], default='todo', max_length=20, verbose_name='Status')),
                ('energy_level', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta')], default='medium', max_length=10, verbose_name='Nível de energia')),
                ('estimated_minutes', models.IntegerField(blank=True, null=True, verbose_name='Minutos estimados')),
                ('scheduled_date', models.CharField(blank=True, max_length=10, verbose_name='Data agendada')),
                ('is_top_priority', models.BooleanField(default=False, verbose_name='Prioridade máxima')),
                ('is_two_minute_task', models.BooleanField(default=False, verbose_name='Tarefa de 2 minutos')),
                ('project_id', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='Projeto')),
                ('completed_at', models.BigIntegerField(blank=True, null=True, verbose_name='Concluído em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.BigIntegerField(verbose_name='Criado em (timestamp)')),
                ('updated_at', models.BigIntegerField(verbose_name='Atualizado em (timestamp)')),
                ('deleted_at', models.BigIntegerField(blank=True, null=True, verbose_name='Deletado em (timestamp)')),
                ('sync_version', models.BigIntegerField(db_index=True, default=0, verbose_name='Versão de sync')),
                ('settings_data', models.JSONField(default=dict, verbose_name='Configurações')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Configuração do Usuário',
                'verbose_name_plural': 'Configurações dos Usuários',
            },
        ),
        migrations.CreateModel(
            name='HabitLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.BigIntegerField(verbose_name='Criado em (timestamp)')),
                ('updated_at', models.BigIntegerField(verbose_name='Atualizado em (timestamp)')),
                ('deleted_at', models.BigIntegerField(blank=True, null=True, verbose_name='Deletado em (timestamp)')),
                ('sync_version', models.BigIntegerField(db_index=True, default=0, verbose_name='Versão de sync')),
                ('habit_id', models.UUIDField(db_index=True, verbose_name='Hábito')),
                ('date', models.CharField(db_index=True, max_length=10, verbose_name='Data')),
                ('completed_at', models.BigIntegerField(verbose_name='Concluído em')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Hábito',
                'verbose_name_plural': 'Logs de Hábitos',
                'ordering': ['-date'],
                'unique_together': {('user', 'habit_id', 'date')},
            },
        ),
    ]
