# Generated by Django 5.0.1 on 2026-01-30 22:50

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_kr_target_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarblock",
            name="description",
            field=models.TextField(blank=True, verbose_name="Descrição"),
        ),
        migrations.AddField(
            model_name="calendarblock",
            name="habit_id",
            field=models.UUIDField(blank=True, null=True, verbose_name="Hábito"),
        ),
        migrations.AddField(
            model_name="calendarblock",
            name="type",
            field=models.CharField(blank=True, max_length=20, verbose_name="Tipo"),
        ),
        migrations.AddField(
            model_name="goal",
            name="description",
            field=models.TextField(blank=True, verbose_name="Descrição"),
        ),
        migrations.AddField(
            model_name="habit",
            name="key_result_id",
            field=models.UUIDField(
                blank=True, db_index=True, null=True, verbose_name="Resultado chave"
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="minimum_version",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Versão mínima"
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="times_per_week",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Vezes por semana"
            ),
        ),
        migrations.AddField(
            model_name="keyresult",
            name="current_value",
            field=models.FloatField(default=0, verbose_name="Valor atual"),
        ),
        migrations.AddField(
            model_name="keyresult",
            name="target_value",
            field=models.FloatField(default=1, verbose_name="Valor alvo"),
        ),
        migrations.AddField(
            model_name="keyresult",
            name="unit",
            field=models.CharField(blank=True, max_length=50, verbose_name="Unidade"),
        ),
        migrations.AddField(
            model_name="pomodorosession",
            name="aborted",
            field=models.BooleanField(default=False, verbose_name="Abortado"),
        ),
        migrations.AddField(
            model_name="pomodorosession",
            name="actual_minutes",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Realizado (minutos)"
            ),
        ),
        migrations.AddField(
            model_name="pomodorosession",
            name="completed",
            field=models.BooleanField(default=False, verbose_name="Concluído"),
        ),
        migrations.AddField(
            model_name="pomodorosession",
            name="date",
            field=models.CharField(blank=True, max_length=10, verbose_name="Data"),
        ),
        migrations.AddField(
            model_name="pomodorosession",
            name="interruptions_count",
            field=models.IntegerField(default=0, verbose_name="Interrupções"),
        ),
        migrations.AddField(
            model_name="pomodorosession",
            name="planned_minutes",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Planejado (minutos)"
            ),
        ),
        migrations.AddField(
            model_name="pomodorosession",
            name="preset_id",
            field=models.UUIDField(
                blank=True, db_index=True, null=True, verbose_name="Preset"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="tags",
            field=models.JSONField(blank=True, default=list, verbose_name="Tags"),
        ),
        migrations.AddField(
            model_name="task",
            name="client_status",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Status cliente"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="description",
            field=models.TextField(blank=True, verbose_name="Descrição"),
        ),
        migrations.AddField(
            model_name="task",
            name="key_result_id",
            field=models.UUIDField(
                blank=True, db_index=True, null=True, verbose_name="Resultado chave"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="tags",
            field=models.JSONField(blank=True, default=list, verbose_name="Tags"),
        ),
        migrations.AlterField(
            model_name="pomodorosession",
            name="duration_minutes",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Duração (minutos)"
            ),
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.BigIntegerField(verbose_name="Criado em (timestamp)"),
                ),
                (
                    "updated_at",
                    models.BigIntegerField(verbose_name="Atualizado em (timestamp)"),
                ),
                (
                    "deleted_at",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Deletado em (timestamp)"
                    ),
                ),
                (
                    "sync_version",
                    models.BigIntegerField(
                        db_index=True, default=0, verbose_name="Versão de sync"
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Título")),
                ("author", models.CharField(max_length=200, verbose_name="Autor")),
                ("total_pages", models.IntegerField(verbose_name="Total de páginas")),
                ("current_page", models.IntegerField(verbose_name="Página atual")),
                (
                    "start_date",
                    models.CharField(max_length=10, verbose_name="Data de início"),
                ),
                (
                    "target_end_date",
                    models.CharField(max_length=10, verbose_name="Data alvo"),
                ),
                ("status", models.CharField(max_length=20, verbose_name="Status")),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Livro",
                "verbose_name_plural": "Livros",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConsentLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.BigIntegerField(verbose_name="Criado em (timestamp)"),
                ),
                (
                    "updated_at",
                    models.BigIntegerField(verbose_name="Atualizado em (timestamp)"),
                ),
                (
                    "deleted_at",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Deletado em (timestamp)"
                    ),
                ),
                (
                    "sync_version",
                    models.BigIntegerField(
                        db_index=True, default=0, verbose_name="Versão de sync"
                    ),
                ),
                (
                    "consent_type",
                    models.CharField(
                        max_length=50, verbose_name="Tipo de consentimento"
                    ),
                ),
                (
                    "granted",
                    models.BooleanField(verbose_name="Consentimento concedido"),
                ),
                ("timestamp", models.BigIntegerField(verbose_name="Timestamp")),
                (
                    "ip_address",
                    models.CharField(blank=True, max_length=100, verbose_name="IP"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consentimento",
                "verbose_name_plural": "Consentimentos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DataExport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.BigIntegerField(verbose_name="Criado em (timestamp)"),
                ),
                (
                    "updated_at",
                    models.BigIntegerField(verbose_name="Atualizado em (timestamp)"),
                ),
                (
                    "deleted_at",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Deletado em (timestamp)"
                    ),
                ),
                (
                    "sync_version",
                    models.BigIntegerField(
                        db_index=True, default=0, verbose_name="Versão de sync"
                    ),
                ),
                (
                    "export_type",
                    models.CharField(max_length=30, verbose_name="Tipo de exportação"),
                ),
                ("status", models.CharField(max_length=20, verbose_name="Status")),
                ("data", models.TextField(blank=True, verbose_name="Dados")),
                (
                    "completed_at",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Concluído em"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exportação",
                "verbose_name_plural": "Exportações",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DietMealEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.BigIntegerField(verbose_name="Criado em (timestamp)"),
                ),
                (
                    "updated_at",
                    models.BigIntegerField(verbose_name="Atualizado em (timestamp)"),
                ),
                (
                    "deleted_at",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Deletado em (timestamp)"
                    ),
                ),
                (
                    "sync_version",
                    models.BigIntegerField(
                        db_index=True, default=0, verbose_name="Versão de sync"
                    ),
                ),
                (
                    "date",
                    models.CharField(db_index=True, max_length=10, verbose_name="Data"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nome")),
                ("time_minutes", models.IntegerField(verbose_name="Horário (min)")),
                (
                    "foods",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Alimentos"
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Concluído"),
                ),
                (
                    "completed_at",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Concluído em"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Refeição",
                "verbose_name_plural": "Refeições",
                "ordering": ["-date", "time_minutes"],
            },
        ),
        migrations.CreateModel(
            name="DietMealTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.BigIntegerField(verbose_name="Criado em (timestamp)"),
                ),
                (
                    "updated_at",
                    models.BigIntegerField(verbose_name="Atualizado em (timestamp)"),
                ),
                (
                    "deleted_at",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Deletado em (timestamp)"
                    ),
                ),
                (
                    "sync_version",
                    models.BigIntegerField(
                        db_index=True, default=0, verbose_name="Versão de sync"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nome")),
                (
                    "default_time_minutes",
                    models.IntegerField(verbose_name="Horário padrão (min)"),
                ),
                (
                    "foods",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Alimentos"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Template de Refeição",
                "verbose_name_plural": "Templates de Refeição",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FinanceAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.BigIntegerField(verbose_name="Criado em (timestamp)"),
                ),
                (
                    "updated_at",
                    models.BigIntegerField(verbose_name="Atualizado em (timestamp)"),
                ),
                (
                    "deleted_at",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Deletado em (timestamp)"
                    ),
                ),
                (
                    "sync_version",
                    models.BigIntegerField(
                        db_index=True, default=0, verbose_name="Versão de sync"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nome")),
                ("type", models.CharField(max_length=20, verbose_name="Tipo")),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12, verbose_name="Saldo"
                    ),
                ),
                (
                    "color",
                    models.CharField(blank=True, max_length=20, verbose_name="Cor"),
                ),
                (
                    "icon",
                    models.CharField(blank=True, max_length=50, verbose_name="Ícone"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conta Financeira",
                "verbose_name_plural": "Contas Financeiras",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FinanceAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.BigIntegerField(verbose_name="Criado em (timestamp)"),
                ),
                (
                    "updated_at",
                    models.BigIntegerField(verbose_name="Atualizado em (timestamp)"),
                ),
                (
                    "deleted_at",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Deletado em (timestamp)"
                    ),
                ),
                (
                    "sync_version",
                    models.BigIntegerField(
                        db_index=True, default=0, verbose_name="Versão de sync"
                    ),
                ),
                ("action", models.CharField(max_length=100, verbose_name="Ação")),
                (
                    "entity_type",
                    models.CharField(max_length=20, verbose_name="Tipo de entidade"),
                ),
                (
                    "entity_id",
                    models.CharField(max_length=100, verbose_name="ID da entidade"),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="Metadata"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log Financeiro",
                "verbose_name_plural": "Logs Financeiros",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FinanceCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.BigIntegerField(verbose_name="Criado em (timestamp)"),
                ),
                (
                    "updated_at",
                    models.BigIntegerField(verbose_name="Atualizado em (timestamp)"),
                ),
                (
                    "deleted_at",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Deletado em (timestamp)"
                    ),
                ),
                (
                    "sync_version",
                    models.BigIntegerField(
                        db_index=True, default=0, verbose_name="Versão de sync"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nome")),
                ("type", models.CharField(max_length=20, verbose_name="Tipo")),
                (
                    "color",
                    models.CharField(blank=True, max_length=20, verbose_name="Cor"),
                ),
                (
                    "icon",
                    models.CharField(blank=True, max_length=50, verbose_name="Ícone"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoria Financeira",
                "verbose_name_plural": "Categorias Financeiras",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FixedExpense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.BigIntegerField(verbose_name="Criado em (timestamp)"),
                ),
                (
                    "updated_at",
                    models.BigIntegerField(verbose_name="Atualizado em (timestamp)"),
                ),
                (
                    "deleted_at",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Deletado em (timestamp)"
                    ),
                ),
                (
                    "sync_version",
                    models.BigIntegerField(
                        db_index=True, default=0, verbose_name="Versão de sync"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nome")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor"
                    ),
                ),
                (
                    "category_id",
                    models.UUIDField(db_index=True, verbose_name="Categoria"),
                ),
                ("account_id", models.UUIDField(db_index=True, verbose_name="Conta")),
                (
                    "frequency",
                    models.CharField(max_length=20, verbose_name="Frequência"),
                ),
                (
                    "day_of_month",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Dia do mês"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Despesa Fixa",
                "verbose_name_plural": "Despesas Fixas",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GoogleCalendarConnection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.BigIntegerField(verbose_name="Criado em (timestamp)"),
                ),
                (
                    "updated_at",
                    models.BigIntegerField(verbose_name="Atualizado em (timestamp)"),
                ),
                (
                    "deleted_at",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Deletado em (timestamp)"
                    ),
                ),
                (
                    "sync_version",
                    models.BigIntegerField(
                        db_index=True, default=0, verbose_name="Versão de sync"
                    ),
                ),
                (
                    "connected",
                    models.BooleanField(default=False, verbose_name="Conectado"),
                ),
                (
                    "connected_at",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Conectado em"
                    ),
                ),
                (
                    "disconnected_at",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Desconectado em"
                    ),
                ),
                (
                    "last_sync_at",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Última sincronização"
                    ),
                ),
                (
                    "access_token",
                    models.TextField(blank=True, verbose_name="Access token"),
                ),
                (
                    "refresh_token",
                    models.TextField(blank=True, verbose_name="Refresh token"),
                ),
                (
                    "expires_at",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Expira em"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conexão Google Calendar",
                "verbose_name_plural": "Conexões Google Calendar",
            },
        ),
        migrations.CreateModel(
            name="GoogleCalendarEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.BigIntegerField(verbose_name="Criado em (timestamp)"),
                ),
                (
                    "updated_at",
                    models.BigIntegerField(verbose_name="Atualizado em (timestamp)"),
                ),
                (
                    "deleted_at",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Deletado em (timestamp)"
                    ),
                ),
                (
                    "sync_version",
                    models.BigIntegerField(
                        db_index=True, default=0, verbose_name="Versão de sync"
                    ),
                ),
                (
                    "google_event_id",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="ID Google"
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Título")),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "start_time",
                    models.IntegerField(
                        verbose_name="Início (minutos desde meia-noite)"
                    ),
                ),
                (
                    "end_time",
                    models.IntegerField(verbose_name="Fim (minutos desde meia-noite)"),
                ),
                (
                    "date",
                    models.CharField(db_index=True, max_length=10, verbose_name="Data"),
                ),
                (
                    "is_read_only",
                    models.BooleanField(default=True, verbose_name="Somente leitura"),
                ),
                (
                    "last_synced_at",
                    models.BigIntegerField(verbose_name="Sincronizado em"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento Google Calendar",
                "verbose_name_plural": "Eventos Google Calendar",
                "ordering": ["date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="Income",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.BigIntegerField(verbose_name="Criado em (timestamp)"),
                ),
                (
                    "updated_at",
                    models.BigIntegerField(verbose_name="Atualizado em (timestamp)"),
                ),
                (
                    "deleted_at",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Deletado em (timestamp)"
                    ),
                ),
                (
                    "sync_version",
                    models.BigIntegerField(
                        db_index=True, default=0, verbose_name="Versão de sync"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nome")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor"
                    ),
                ),
                ("type", models.CharField(max_length=20, verbose_name="Tipo")),
                (
                    "category_id",
                    models.UUIDField(
                        blank=True, db_index=True, null=True, verbose_name="Categoria"
                    ),
                ),
                ("account_id", models.UUIDField(db_index=True, verbose_name="Conta")),
                (
                    "frequency",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Frequência"
                    ),
                ),
                (
                    "day_of_month",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Dia do mês"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Renda",
                "verbose_name_plural": "Rendas",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PDFDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.BigIntegerField(verbose_name="Criado em (timestamp)"),
                ),
                (
                    "updated_at",
                    models.BigIntegerField(verbose_name="Atualizado em (timestamp)"),
                ),
                (
                    "deleted_at",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Deletado em (timestamp)"
                    ),
                ),
                (
                    "sync_version",
                    models.BigIntegerField(
                        db_index=True, default=0, verbose_name="Versão de sync"
                    ),
                ),
                (
                    "file_name",
                    models.CharField(max_length=300, verbose_name="Nome do arquivo"),
                ),
                ("file_size", models.IntegerField(verbose_name="Tamanho do arquivo")),
                ("total_pages", models.IntegerField(verbose_name="Total de páginas")),
                ("current_page", models.IntegerField(verbose_name="Página atual")),
                (
                    "last_opened_at",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Última abertura"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento PDF",
                "verbose_name_plural": "Documentos PDF",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PDFHighlight",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.BigIntegerField(verbose_name="Criado em (timestamp)"),
                ),
                (
                    "updated_at",
                    models.BigIntegerField(verbose_name="Atualizado em (timestamp)"),
                ),
                (
                    "deleted_at",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Deletado em (timestamp)"
                    ),
                ),
                (
                    "sync_version",
                    models.BigIntegerField(
                        db_index=True, default=0, verbose_name="Versão de sync"
                    ),
                ),
                (
                    "document_id",
                    models.UUIDField(db_index=True, verbose_name="Documento"),
                ),
                ("page_number", models.IntegerField(verbose_name="Página")),
                ("text", models.TextField(verbose_name="Texto")),
                ("color", models.CharField(max_length=20, verbose_name="Cor")),
                ("note", models.TextField(blank=True, verbose_name="Nota")),
                ("position", models.JSONField(verbose_name="Posição")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Highlight PDF",
                "verbose_name_plural": "Highlights PDF",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PomodoroPreset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.BigIntegerField(verbose_name="Criado em (timestamp)"),
                ),
                (
                    "updated_at",
                    models.BigIntegerField(verbose_name="Atualizado em (timestamp)"),
                ),
                (
                    "deleted_at",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Deletado em (timestamp)"
                    ),
                ),
                (
                    "sync_version",
                    models.BigIntegerField(
                        db_index=True, default=0, verbose_name="Versão de sync"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nome")),
                ("focus_duration", models.IntegerField(verbose_name="Foco (min)")),
                ("break_duration", models.IntegerField(verbose_name="Pausa (min)")),
                (
                    "long_break_duration",
                    models.IntegerField(default=15, verbose_name="Pausa longa (min)"),
                ),
                (
                    "sessions_before_long_break",
                    models.IntegerField(
                        default=4, verbose_name="Sessões antes da pausa longa"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="Padrão"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Preset Pomodoro",
                "verbose_name_plural": "Presets Pomodoro",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReadingLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.BigIntegerField(verbose_name="Criado em (timestamp)"),
                ),
                (
                    "updated_at",
                    models.BigIntegerField(verbose_name="Atualizado em (timestamp)"),
                ),
                (
                    "deleted_at",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Deletado em (timestamp)"
                    ),
                ),
                (
                    "sync_version",
                    models.BigIntegerField(
                        db_index=True, default=0, verbose_name="Versão de sync"
                    ),
                ),
                ("book_id", models.UUIDField(db_index=True, verbose_name="Livro")),
                (
                    "date",
                    models.CharField(db_index=True, max_length=10, verbose_name="Data"),
                ),
                ("pages_read", models.IntegerField(verbose_name="Páginas lidas")),
                ("start_page", models.IntegerField(verbose_name="Página inicial")),
                ("end_page", models.IntegerField(verbose_name="Página final")),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Leitura",
                "verbose_name_plural": "Logs de Leitura",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="RecordedStudySession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.BigIntegerField(verbose_name="Criado em (timestamp)"),
                ),
                (
                    "updated_at",
                    models.BigIntegerField(verbose_name="Atualizado em (timestamp)"),
                ),
                (
                    "deleted_at",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Deletado em (timestamp)"
                    ),
                ),
                (
                    "sync_version",
                    models.BigIntegerField(
                        db_index=True, default=0, verbose_name="Versão de sync"
                    ),
                ),
                ("subject_id", models.UUIDField(db_index=True, verbose_name="Matéria")),
                (
                    "date",
                    models.CharField(db_index=True, max_length=10, verbose_name="Data"),
                ),
                (
                    "duration_minutes",
                    models.IntegerField(verbose_name="Duração (minutos)"),
                ),
                (
                    "transcription",
                    models.TextField(blank=True, verbose_name="Transcrição"),
                ),
                ("ai_summary", models.TextField(blank=True, verbose_name="Resumo IA")),
                (
                    "ai_questions",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Perguntas IA"
                    ),
                ),
                (
                    "review_schedule",
                    models.JSONField(blank=True, default=list, verbose_name="Revisões"),
                ),
                (
                    "consent_log_id",
                    models.UUIDField(db_index=True, verbose_name="Consentimento"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sessão Gravada",
                "verbose_name_plural": "Sessões Gravadas",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Reference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.BigIntegerField(verbose_name="Criado em (timestamp)"),
                ),
                (
                    "updated_at",
                    models.BigIntegerField(verbose_name="Atualizado em (timestamp)"),
                ),
                (
                    "deleted_at",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Deletado em (timestamp)"
                    ),
                ),
                (
                    "sync_version",
                    models.BigIntegerField(
                        db_index=True, default=0, verbose_name="Versão de sync"
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Título")),
                ("content", models.TextField(verbose_name="Conteúdo")),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, verbose_name="Tags"),
                ),
                ("source_url", models.TextField(blank=True, verbose_name="URL fonte")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Referência",
                "verbose_name_plural": "Referências",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewScheduleItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.BigIntegerField(verbose_name="Criado em (timestamp)"),
                ),
                (
                    "updated_at",
                    models.BigIntegerField(verbose_name="Atualizado em (timestamp)"),
                ),
                (
                    "deleted_at",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Deletado em (timestamp)"
                    ),
                ),
                (
                    "sync_version",
                    models.BigIntegerField(
                        db_index=True, default=0, verbose_name="Versão de sync"
                    ),
                ),
                (
                    "recorded_session_id",
                    models.UUIDField(db_index=True, verbose_name="Sessão gravada"),
                ),
                (
                    "scheduled_date",
                    models.CharField(
                        db_index=True, max_length=10, verbose_name="Data agendada"
                    ),
                ),
                (
                    "completed",
                    models.BooleanField(default=False, verbose_name="Concluído"),
                ),
                (
                    "completed_at",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Concluído em"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Revisão",
                "verbose_name_plural": "Revisões",
                "ordering": ["scheduled_date"],
            },
        ),
        migrations.CreateModel(
            name="StudySession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.BigIntegerField(verbose_name="Criado em (timestamp)"),
                ),
                (
                    "updated_at",
                    models.BigIntegerField(verbose_name="Atualizado em (timestamp)"),
                ),
                (
                    "deleted_at",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Deletado em (timestamp)"
                    ),
                ),
                (
                    "sync_version",
                    models.BigIntegerField(
                        db_index=True, default=0, verbose_name="Versão de sync"
                    ),
                ),
                ("subject_id", models.UUIDField(db_index=True, verbose_name="Matéria")),
                (
                    "date",
                    models.CharField(db_index=True, max_length=10, verbose_name="Data"),
                ),
                (
                    "start_time",
                    models.IntegerField(
                        verbose_name="Início (minutos desde meia-noite)"
                    ),
                ),
                (
                    "end_time",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Fim (minutos desde meia-noite)",
                    ),
                ),
                (
                    "duration_minutes",
                    models.IntegerField(verbose_name="Duração (minutos)"),
                ),
                (
                    "quick_notes",
                    models.TextField(blank=True, verbose_name="Notas rápidas"),
                ),
                (
                    "self_test_questions",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Autoavaliação"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sessão de Estudo",
                "verbose_name_plural": "Sessões de Estudo",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.BigIntegerField(verbose_name="Criado em (timestamp)"),
                ),
                (
                    "updated_at",
                    models.BigIntegerField(verbose_name="Atualizado em (timestamp)"),
                ),
                (
                    "deleted_at",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Deletado em (timestamp)"
                    ),
                ),
                (
                    "sync_version",
                    models.BigIntegerField(
                        db_index=True, default=0, verbose_name="Versão de sync"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nome")),
                (
                    "color",
                    models.CharField(blank=True, max_length=20, verbose_name="Cor"),
                ),
                (
                    "icon",
                    models.CharField(blank=True, max_length=50, verbose_name="Ícone"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Matéria",
                "verbose_name_plural": "Matérias",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.BigIntegerField(verbose_name="Criado em (timestamp)"),
                ),
                (
                    "updated_at",
                    models.BigIntegerField(verbose_name="Atualizado em (timestamp)"),
                ),
                (
                    "deleted_at",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Deletado em (timestamp)"
                    ),
                ),
                (
                    "sync_version",
                    models.BigIntegerField(
                        db_index=True, default=0, verbose_name="Versão de sync"
                    ),
                ),
                ("type", models.CharField(max_length=20, verbose_name="Tipo")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor"
                    ),
                ),
                (
                    "date",
                    models.CharField(db_index=True, max_length=10, verbose_name="Data"),
                ),
                (
                    "category_id",
                    models.UUIDField(
                        blank=True, db_index=True, null=True, verbose_name="Categoria"
                    ),
                ),
                ("account_id", models.UUIDField(db_index=True, verbose_name="Conta")),
                ("description", models.TextField(verbose_name="Descrição")),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "is_recurring",
                    models.BooleanField(default=False, verbose_name="Recorrente"),
                ),
                (
                    "parent_transaction_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="Transação pai",
                    ),
                ),
                (
                    "ai_suggested",
                    models.BooleanField(default=False, verbose_name="Sugestão IA"),
                ),
                (
                    "ai_metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Metadata IA"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transação",
                "verbose_name_plural": "Transações",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="WellnessCheckIn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.BigIntegerField(verbose_name="Criado em (timestamp)"),
                ),
                (
                    "updated_at",
                    models.BigIntegerField(verbose_name="Atualizado em (timestamp)"),
                ),
                (
                    "deleted_at",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Deletado em (timestamp)"
                    ),
                ),
                (
                    "sync_version",
                    models.BigIntegerField(
                        db_index=True, default=0, verbose_name="Versão de sync"
                    ),
                ),
                (
                    "date",
                    models.CharField(db_index=True, max_length=10, verbose_name="Data"),
                ),
                (
                    "sleep_hours",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Horas de sono"
                    ),
                ),
                (
                    "energy_level",
                    models.CharField(blank=True, max_length=10, verbose_name="Energia"),
                ),
                (
                    "mood",
                    models.CharField(blank=True, max_length=10, verbose_name="Humor"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Check-in",
                "verbose_name_plural": "Check-ins",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="WellnessDayAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.BigIntegerField(verbose_name="Criado em (timestamp)"),
                ),
                (
                    "updated_at",
                    models.BigIntegerField(verbose_name="Atualizado em (timestamp)"),
                ),
                (
                    "deleted_at",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Deletado em (timestamp)"
                    ),
                ),
                (
                    "sync_version",
                    models.BigIntegerField(
                        db_index=True, default=0, verbose_name="Versão de sync"
                    ),
                ),
                (
                    "program_id",
                    models.UUIDField(db_index=True, verbose_name="Programa"),
                ),
                ("day", models.IntegerField(verbose_name="Dia")),
                ("action", models.TextField(verbose_name="Ação")),
                (
                    "completed",
                    models.BooleanField(default=False, verbose_name="Concluído"),
                ),
                (
                    "completed_at",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Concluído em"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ação de Bem-estar",
                "verbose_name_plural": "Ações de Bem-estar",
                "ordering": ["program_id", "day"],
            },
        ),
        migrations.CreateModel(
            name="WellnessProgram",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.BigIntegerField(verbose_name="Criado em (timestamp)"),
                ),
                (
                    "updated_at",
                    models.BigIntegerField(verbose_name="Atualizado em (timestamp)"),
                ),
                (
                    "deleted_at",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Deletado em (timestamp)"
                    ),
                ),
                (
                    "sync_version",
                    models.BigIntegerField(
                        db_index=True, default=0, verbose_name="Versão de sync"
                    ),
                ),
                ("type", models.CharField(max_length=20, verbose_name="Tipo")),
                ("duration", models.IntegerField(verbose_name="Duração (dias)")),
                (
                    "start_date",
                    models.CharField(max_length=10, verbose_name="Data de início"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "current_day",
                    models.IntegerField(default=1, verbose_name="Dia atual"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Programa de Bem-estar",
                "verbose_name_plural": "Programas de Bem-estar",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkoutExercise",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.BigIntegerField(verbose_name="Criado em (timestamp)"),
                ),
                (
                    "updated_at",
                    models.BigIntegerField(verbose_name="Atualizado em (timestamp)"),
                ),
                (
                    "deleted_at",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Deletado em (timestamp)"
                    ),
                ),
                (
                    "sync_version",
                    models.BigIntegerField(
                        db_index=True, default=0, verbose_name="Versão de sync"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nome")),
                (
                    "muscle_group",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Grupo muscular"
                    ),
                ),
                (
                    "equipment",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Equipamento"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exercício",
                "verbose_name_plural": "Exercícios",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WorkoutPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.BigIntegerField(verbose_name="Criado em (timestamp)"),
                ),
                (
                    "updated_at",
                    models.BigIntegerField(verbose_name="Atualizado em (timestamp)"),
                ),
                (
                    "deleted_at",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Deletado em (timestamp)"
                    ),
                ),
                (
                    "sync_version",
                    models.BigIntegerField(
                        db_index=True, default=0, verbose_name="Versão de sync"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nome")),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "is_archived",
                    models.BooleanField(default=False, verbose_name="Arquivado"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plano de Treino",
                "verbose_name_plural": "Planos de Treino",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WorkoutPlanItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.BigIntegerField(verbose_name="Criado em (timestamp)"),
                ),
                (
                    "updated_at",
                    models.BigIntegerField(verbose_name="Atualizado em (timestamp)"),
                ),
                (
                    "deleted_at",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Deletado em (timestamp)"
                    ),
                ),
                (
                    "sync_version",
                    models.BigIntegerField(
                        db_index=True, default=0, verbose_name="Versão de sync"
                    ),
                ),
                ("plan_id", models.UUIDField(db_index=True, verbose_name="Plano")),
                (
                    "exercise_id",
                    models.UUIDField(db_index=True, verbose_name="Exercício"),
                ),
                ("order", models.IntegerField(verbose_name="Ordem")),
                (
                    "target_sets",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Séries alvo"
                    ),
                ),
                (
                    "target_reps_min",
                    models.IntegerField(blank=True, null=True, verbose_name="Reps mín"),
                ),
                (
                    "target_reps_max",
                    models.IntegerField(blank=True, null=True, verbose_name="Reps máx"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item do Plano",
                "verbose_name_plural": "Itens do Plano",
                "ordering": ["plan_id", "order"],
            },
        ),
        migrations.CreateModel(
            name="WorkoutSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.BigIntegerField(verbose_name="Criado em (timestamp)"),
                ),
                (
                    "updated_at",
                    models.BigIntegerField(verbose_name="Atualizado em (timestamp)"),
                ),
                (
                    "deleted_at",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Deletado em (timestamp)"
                    ),
                ),
                (
                    "sync_version",
                    models.BigIntegerField(
                        db_index=True, default=0, verbose_name="Versão de sync"
                    ),
                ),
                (
                    "plan_id",
                    models.UUIDField(
                        blank=True, db_index=True, null=True, verbose_name="Plano"
                    ),
                ),
                (
                    "date",
                    models.CharField(db_index=True, max_length=10, verbose_name="Data"),
                ),
                ("started_at", models.BigIntegerField(verbose_name="Início")),
                (
                    "ended_at",
                    models.BigIntegerField(blank=True, null=True, verbose_name="Fim"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sessão de Treino",
                "verbose_name_plural": "Sessões de Treino",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="WorkoutSetLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.BigIntegerField(verbose_name="Criado em (timestamp)"),
                ),
                (
                    "updated_at",
                    models.BigIntegerField(verbose_name="Atualizado em (timestamp)"),
                ),
                (
                    "deleted_at",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Deletado em (timestamp)"
                    ),
                ),
                (
                    "sync_version",
                    models.BigIntegerField(
                        db_index=True, default=0, verbose_name="Versão de sync"
                    ),
                ),
                ("session_id", models.UUIDField(db_index=True, verbose_name="Sessão")),
                (
                    "exercise_id",
                    models.UUIDField(db_index=True, verbose_name="Exercício"),
                ),
                ("set_index", models.IntegerField(verbose_name="Série")),
                ("reps", models.IntegerField(verbose_name="Repetições")),
                ("weight", models.FloatField(verbose_name="Peso")),
                ("unit", models.CharField(max_length=5, verbose_name="Unidade")),
                (
                    "is_warmup",
                    models.BooleanField(default=False, verbose_name="Aquecimento"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Série",
                "verbose_name_plural": "Logs de Série",
                "ordering": ["-created_at"],
            },
        ),
    ]
