# Generated by Django 5.0.1 on 2026-01-30 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_calendarblock_description_calendarblock_habit_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inboxitem",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notas"),
        ),
    ]
