# Generated by Django 5.0.1 on 2026-01-31 02:44

import apps.core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_inboxitem_notes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.BigIntegerField(verbose_name="Criado em (timestamp)"),
                ),
                (
                    "updated_at",
                    models.BigIntegerField(verbose_name="Atualizado em (timestamp)"),
                ),
                (
                    "deleted_at",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Deletado em (timestamp)"
                    ),
                ),
                (
                    "sync_version",
                    models.BigIntegerField(
                        db_index=True, default=0, verbose_name="Versão de sync"
                    ),
                ),
                (
                    "date",
                    models.CharField(db_index=True, max_length=10, verbose_name="Data"),
                ),
                ("content", models.TextField(blank=True, verbose_name="Conteudo")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota Diaria",
                "verbose_name_plural": "Notas Diarias",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="PDFFile",
            fields=[
                (
                    "document_id",
                    models.UUIDField(
                        primary_key=True, serialize=False, verbose_name="Documento"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.core.models.pdf_upload_path,
                        verbose_name="Arquivo",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(max_length=300, verbose_name="Nome do arquivo"),
                ),
                (
                    "file_size",
                    models.BigIntegerField(verbose_name="Tamanho do arquivo"),
                ),
                (
                    "content_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Content-Type"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pdf_files",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Arquivo PDF",
                "verbose_name_plural": "Arquivos PDF",
                "ordering": ["-created_at"],
            },
        ),
    ]
