# Generated by Django 5.0.1 on 2026-02-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_dailynote_pdffile"),
    ]

    operations = [
        migrations.AddField(
            model_name="fixedexpense",
            name="auto_confirm",
            field=models.BooleanField(
                default=False, verbose_name="Confirmação automática"
            ),
        ),
        migrations.AddField(
            model_name="fixedexpense",
            name="last_confirmed_month",
            field=models.CharField(
                blank=True,
                max_length=7,
                null=True,
                verbose_name="Último mês confirmado",
            ),
        ),
        migrations.AddField(
            model_name="income",
            name="auto_confirm",
            field=models.BooleanField(
                default=False, verbose_name="Confirmação automática"
            ),
        ),
        migrations.AddField(
            model_name="income",
            name="last_confirmed_month",
            field=models.CharField(
                blank=True,
                max_length=7,
                null=True,
                verbose_name="Último mês confirmado",
            ),
        ),
    ]
