# Generated by Django 5.2.11 on 2026-02-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_safe_pdffile_pk_workout_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietmealtemplate',
            name='days_of_week',
            field=models.JSONField(blank=True, default=list, verbose_name='Dias da semana'),
        ),
        migrations.AddField(
            model_name='dietmealtemplate',
            name='frequency',
            field=models.CharField(choices=[('manual', 'Manual'), ('daily', 'Diário'), ('weekdays', 'Dias úteis'), ('weekends', 'Finais de semana'), ('custom', 'Personalizado')], default='manual', max_length=20, verbose_name='Frequência'),
        ),
    ]
