# Generated by Django 5.2.12 on 2026-03-13 00:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_dietmealtemplate_days_of_week_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.BigIntegerField(verbose_name='Criado em (timestamp)')),
                ('updated_at', models.BigIntegerField(verbose_name='Atualizado em (timestamp)')),
                ('deleted_at', models.BigIntegerField(blank=True, null=True, verbose_name='Deletado em (timestamp)')),
                ('sync_version', models.BigIntegerField(db_index=True, default=0, verbose_name='Versão de sync')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('type', models.CharField(choices=[('cdb', 'CDB'), ('lci', 'LCI'), ('lca', 'LCA'), ('tesouro', 'Tesouro Direto'), ('fundo', 'Fundo de Investimento'), ('acao', 'Ação'), ('fii', 'FII'), ('crypto', 'Criptomoeda'), ('poupanca', 'Poupança'), ('previdencia', 'Previdência'), ('other', 'Outro')], max_length=30, verbose_name='Tipo')),
                ('institution', models.CharField(blank=True, max_length=200, verbose_name='Instituição')),
                ('amount_invested', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor investido')),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor atual')),
                ('start_date', models.CharField(max_length=10, verbose_name='Data de início')),
                ('maturity_date', models.CharField(blank=True, max_length=10, verbose_name='Data de vencimento')),
                ('goal_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Meta de valor')),
                ('goal_name', models.CharField(blank=True, max_length=200, verbose_name='Nome da meta')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Investimento',
                'verbose_name_plural': 'Investimentos',
                'ordering': ['-created_at'],
            },
        ),
    ]
