# Generated by Django 5.0.1 on 2026-03-13 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_investment_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="preferred_time",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Horário preferido"
            ),
        ),
        migrations.AddField(
            model_name="studysession",
            name="final_notes",
            field=models.TextField(blank=True, verbose_name="Notas finais"),
        ),
        migrations.AddField(
            model_name="task",
            name="source_inbox_item_id",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="Item de inbox origem"
            ),
        ),
    ]
