# Generated by Django 5.0.1 on 2026-03-13 04:08
# Fixed: use ADD COLUMN IF NOT EXISTS for idempotent deploy

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_investment_model"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="habit",
                    name="preferred_time",
                    field=models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="Horário preferido",
                    ),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE core_habit ADD COLUMN IF NOT EXISTS preferred_time varchar(20) NOT NULL DEFAULT '';",
                    reverse_sql="ALTER TABLE core_habit DROP COLUMN IF EXISTS preferred_time;",
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="studysession",
                    name="final_notes",
                    field=models.TextField(
                        blank=True, default="", verbose_name="Notas finais"
                    ),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE core_studysession ADD COLUMN IF NOT EXISTS final_notes text NOT NULL DEFAULT '';",
                    reverse_sql="ALTER TABLE core_studysession DROP COLUMN IF EXISTS final_notes;",
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="task",
                    name="source_inbox_item_id",
                    field=models.UUIDField(
                        blank=True, null=True, verbose_name="Item de inbox origem"
                    ),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE core_task ADD COLUMN IF NOT EXISTS source_inbox_item_id uuid NULL;",
                    reverse_sql="ALTER TABLE core_task DROP COLUMN IF EXISTS source_inbox_item_id;",
                ),
            ],
        ),
    ]
