# Generated by Django 5.0.1 on 2026-03-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_add_missing_sync_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="preferred_time",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Horário preferido"
            ),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="final_notes",
            field=models.TextField(blank=True, verbose_name="Notas finais"),
        ),
    ]
