# Generated by Django 5.0.1 on 2026-03-14 04:04

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_widen_last_confirmed_month"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendarblock",
            name="date",
            field=models.CharField(
                db_index=True,
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Data deve estar no formato YYYY-MM-DD.",
                        regex="^\\d{4}-\\d{2}-\\d{2}$",
                    )
                ],
                verbose_name="Data",
            ),
        ),
        migrations.AlterField(
            model_name="dailynote",
            name="date",
            field=models.CharField(
                db_index=True,
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Data deve estar no formato YYYY-MM-DD.",
                        regex="^\\d{4}-\\d{2}-\\d{2}$",
                    )
                ],
                verbose_name="Data",
            ),
        ),
        migrations.AlterField(
            model_name="habitlog",
            name="date",
            field=models.CharField(
                db_index=True,
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Data deve estar no formato YYYY-MM-DD.",
                        regex="^\\d{4}-\\d{2}-\\d{2}$",
                    )
                ],
                verbose_name="Data",
            ),
        ),
        migrations.AlterField(
            model_name="pomodorosession",
            name="date",
            field=models.CharField(
                blank=True,
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Data deve estar no formato YYYY-MM-DD.",
                        regex="^\\d{4}-\\d{2}-\\d{2}$",
                    )
                ],
                verbose_name="Data",
            ),
        ),
        migrations.AddConstraint(
            model_name="dailynote",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("user", "date"),
                name="unique_active_dailynote_per_user_date",
            ),
        ),
    ]
