# Generated by Django 5.2.12 on 2026-03-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_low_priority_audit_fixes'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeaccount',
            name='closing_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Dia de Fechamento'),
        ),
        migrations.AddField(
            model_name='financeaccount',
            name='due_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Dia de Vencimento'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='installment_current',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Parcela atual'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='installment_total',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Total de parcelas'),
        ),
    ]
