# Generated by Django 5.2.12 on 2026-03-14 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_credit_card_and_installment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeaccount',
            name='limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Limite'),
        ),
    ]
