# Generated by Django 5.2.10 on 2026-01-26 02:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('plan_type', models.CharField(choices=[('pro', 'Acorda Pro'), ('pro_ia', 'Acorda Pro IA'), ('lifetime', 'Lifetime (sem IA)')], db_index=True, max_length=20, verbose_name='Tipo')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Mensal'), ('yearly', 'Anual'), ('lifetime', 'Vitalício')], db_index=True, max_length=20, verbose_name='Ciclo')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('currency', models.CharField(default='BRL', max_length=3, verbose_name='Moeda')),
                ('mp_plan_id', models.CharField(blank=True, help_text='ID do plano no Mercado Pago (para assinaturas)', max_length=100, verbose_name='MP Plan ID')),
                ('has_ai', models.BooleanField(default=False, verbose_name='Tem IA')),
                ('ai_requests_limit', models.IntegerField(blank=True, null=True, verbose_name='Limite requisições IA/mês')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'ordering': ['price'],
                'unique_together': {('plan_type', 'billing_cycle')},
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('active', 'Ativa'), ('past_due', 'Inadimplente'), ('cancelled', 'Cancelada'), ('expired', 'Expirada')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('mp_subscription_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='MP Subscription ID')),
                ('mp_payer_id', models.CharField(blank=True, max_length=100, verbose_name='MP Payer ID')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Iniciou em')),
                ('current_period_start', models.DateTimeField(blank=True, null=True, verbose_name='Período atual início')),
                ('current_period_end', models.DateTimeField(blank=True, null=True, verbose_name='Período atual fim')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancelada em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan', verbose_name='Plano')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_type', models.CharField(choices=[('subscription', 'Assinatura'), ('one_time', 'Pagamento Único')], db_index=True, max_length=20, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('refunded', 'Reembolsado'), ('cancelled', 'Cancelado')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('currency', models.CharField(default='BRL', max_length=3, verbose_name='Moeda')),
                ('mp_payment_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='MP Payment ID')),
                ('mp_preference_id', models.CharField(blank=True, max_length=100, verbose_name='MP Preference ID')),
                ('mp_status', models.CharField(blank=True, max_length=50, verbose_name='MP Status')),
                ('mp_status_detail', models.CharField(blank=True, max_length=100, verbose_name='MP Status Detail')),
                ('payer_email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail do pagador')),
                ('payer_name', models.CharField(blank=True, max_length=200, verbose_name='Nome do pagador')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Pago em')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.plan', verbose_name='Plano')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='billing.subscription', verbose_name='Assinatura')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature', models.CharField(db_index=True, max_length=50, verbose_name='Feature')),
                ('date', models.DateField(db_index=True, verbose_name='Data')),
                ('count', models.IntegerField(default=0, verbose_name='Contagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Registro de Uso',
                'verbose_name_plural': 'Registros de Uso',
                'ordering': ['-date'],
                'unique_together': {('user', 'feature', 'date')},
            },
        ),
    ]
