# Generated by Django 5.2.10 on 2026-01-29 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.TextField(blank=True, null=True, verbose_name='Avatar (Data URL)'),
        ),
    ]
