# Generated by Django 5.0.1 on 2026-02-22 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_change_default_appearance_to_dark"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="onboarding_completed",
            field=models.BooleanField(
                default=False, verbose_name="Onboarding concluído"
            ),
        ),
    ]
